
-- Generated by ORDS REST Data Services 25.1.0.r1001652
-- Schema: EDU  Date: Wed Dec 31 05:00:13 2025 
--
        
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'EDU',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'edu',
      p_auto_rest_auth      => TRUE);
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'session_validation',
      p_base_path      => '/validate_session/',
      p_items_per_page => 0,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'session_validation',
      p_pattern        => 'result',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'session_validation',
      p_pattern        => 'result',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
  v_return NUMBER;
BEGIN
  v_return := edu.VALIDATE_SESSION(
                P_APP_ID     => :app_id,
                P_EMPNO => :emp_no,
                P_APP_CS => :app_id,                
                P_SESSION_ID => :session_id
              );

  IF v_return = 1 THEN
    :status   := 200;
    sys.htp.p(''{"is_valid":"1"}'');
  ELSE
    :status   := 401;
     sys.htp.p(''{"is_valid":"0"}'');
  END IF;
END;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'session_validation',
      p_pattern            => 'result',
      p_method             => 'GET',
      p_name               => 'p_app_id',
      p_bind_variable_name => 'app_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => 'mapped here for app_cs');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'session_validation',
      p_pattern            => 'result',
      p_method             => 'GET',
      p_name               => 'p_session_id',
      p_bind_variable_name => 'session_id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'session_validation',
      p_pattern            => 'result',
      p_method             => 'GET',
      p_name               => 'X-APEX-STATUS-CODE',
      p_bind_variable_name => 'status',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'session_validation',
      p_pattern            => 'result',
      p_method             => 'GET',
      p_name               => 'p_emp_no',
      p_bind_variable_name => 'emp_no',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

    
        
COMMIT;

END;
